### ISSUE TITLE
Create loadtests for POST loadtests - small file, large file

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/antenna-loadtests#5]

**Comment by rpappalax** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1314740
rpapa: https://github.com/mozilla/antenna/blob/7af5bf0ee58d9b592890f4eb77023690d24c82e5/antenna/throttler.py
mbrandt, rpapa: http://antenna.readthedocs.io/en/latest/
rpapa: http://antenna.readthedocs.io/en/latest/spec_v1.html#crash-reports-and-the-current-collector
rpapa: https://bugzilla.mozilla.org/show_bug.cgi?id=1314740

**Comment by rpappalax** [comment]
biggest stressor:  slightly less than 20M nginx MAX
and compressed data will force antenna to do most work

**Comment by willkg** [comment]
In our conversation last week, I offered to do a requests-based example for posting crashes. I thought about how to do that most effectively and ended up adding on to the `antenna.mini_poster` module.

https://github.com/mozilla/antenna/blob/master/antenna/mini_poster.py

In that module there's a function for generating the mulidpart/form-data payload, a function for posting a crash using requests and some scaffolding that lets you run it from the command line via:

```
python -m antenna.mini_poster
```

It sets up all the debugging logging so it prints a bunch of stuff regarding what it's doing and the headers it's sending.

Hope that helps! Let me know if there's anything else I can do.

**Comment by willkg** [comment]
As a side note, I'm seriously thinking about extracting that `mini_poster` module and turning it into a library. I don't think I'd use it outside of antenna, but having it separate would make some things easier.

Would that help you? If so, I can do that this week.

**Comment by m8ttyB** [comment]
@willkg uber thanks for your work. I'm futzing with it now.
